// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Education struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userID"`
	School      string  `json:"school"`
	Degree      string  `json:"degree"`
	Major       string  `json:"major"`
	Grade       float64 `json:"grade"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
	Description string  `json:"description"`
}

type Experience struct {
	ID               string `json:"ID"`
	UserID           string `json:"userID"`
	Title            string `json:"title"`
	EmploymentType   string `json:"employmentType"`
	Company          string `json:"company"`
	Location         string `json:"location"`
	StartDate        string `json:"startDate"`
	EndDate          string `json:"endDate"`
	Description      string `json:"description"`
	CurrentlyWorking bool   `json:"currentlyWorking"`
}

type Hashtag struct {
	ID      string `json:"id"`
	Hashtag string `json:"hashtag"`
}

type Job struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Company   string `json:"company"`
	Location  string `json:"location"`
	CreatedAt string `json:"createdAt"`
}

type NewEducation struct {
	UserID      string  `json:"userID"`
	School      string  `json:"school"`
	Degree      string  `json:"degree"`
	Major       string  `json:"major"`
	Grade       float64 `json:"grade"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
	Description string  `json:"description"`
}

type NewExperience struct {
	UserID           string `json:"userID"`
	Title            string `json:"title"`
	EmploymentType   string `json:"employmentType"`
	Company          string `json:"company"`
	Location         string `json:"location"`
	StartDate        string `json:"startDate"`
	EndDate          string `json:"endDate"`
	Description      string `json:"description"`
	CurrentlyWorking bool   `json:"currentlyWorking"`
}

type NewJob struct {
	Title     string `json:"title"`
	Company   string `json:"company"`
	Location  string `json:"location"`
	CreatedAt string `json:"createdAt"`
}

type NewMessage struct {
	Sender     string `json:"sender"`
	RoomID     string `json:"roomID"`
	Text       string `json:"text"`
	ImageURL   string `json:"imageURL"`
	SharedPost string `json:"sharedPost"`
	SharedUser string `json:"sharedUser"`
}

type Notification struct {
	ID        string    `json:"id"`
	Message   string    `json:"message"`
	FromUser  string    `json:"fromUser"`
	ToUser    string    `json:"toUser"`
	CreatedAt time.Time `json:"createdAt"`
}

type ResetPassLink struct {
	ID     string `json:"id"`
	UserID string `json:"userID"`
}

type Search struct {
	Users []*User `json:"Users"`
	Posts []*Post `json:"Posts"`
}

type Invitation struct {
	ID     string `json:"id"`
	UserID string `json:"userID"`
}
