// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Education struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userID"`
	School      string  `json:"school"`
	Degree      string  `json:"degree"`
	Major       string  `json:"major"`
	Grade       float64 `json:"grade"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
	Description string  `json:"description"`
}

type Experience struct {
	ID               string `json:"ID"`
	UserID           string `json:"userID"`
	Title            string `json:"title"`
	EmploymentType   string `json:"employmentType"`
	Company          string `json:"company"`
	Location         string `json:"location"`
	StartDate        string `json:"startDate"`
	EndDate          string `json:"endDate"`
	Description      string `json:"description"`
	CurrentlyWorking bool   `json:"currentlyWorking"`
}

type NewEducation struct {
	UserID      string  `json:"userID"`
	School      string  `json:"school"`
	Degree      string  `json:"degree"`
	Major       string  `json:"major"`
	Grade       float64 `json:"grade"`
	StartDate   string  `json:"startDate"`
	EndDate     string  `json:"endDate"`
	Description string  `json:"description"`
}

type NewExperience struct {
	UserID           string `json:"userID"`
	Title            string `json:"title"`
	EmploymentType   string `json:"employmentType"`
	Company          string `json:"company"`
	Location         string `json:"location"`
	StartDate        string `json:"startDate"`
	EndDate          string `json:"endDate"`
	Description      string `json:"description"`
	CurrentlyWorking bool   `json:"currentlyWorking"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type ResetPassLink struct {
	ID     string `json:"id"`
	UserID string `json:"userID"`
}

type Invitation struct {
	ID     string `json:"id"`
	UserID string `json:"userID"`
}
